# ==============================================================================
# Merged Lakeflow Source: intacct
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from xml.sax.saxutils import escape
import base64
import requests
import xml.etree.ElementTree as ET


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/intacct/intacct_schemas.py
    ########################################################

    PRIMARY_KEY_FIELD = "RECORDNO"
    CURSOR_FIELD = "WHENMODIFIED"

    TABLE_TO_OBJECT: dict[str, str] = {
        "customers": "CUSTOMER",
        "vendors": "VENDOR",
        "invoices": "ARINVOICE",
        "bills": "APBILL",
        "gl_entries": "GLDETAIL",
    }

    OBJECT_TO_TABLE: dict[str, str] = {v: k for k, v in TABLE_TO_OBJECT.items()}

    # XML Gateway pagination bounds (see "Pagination" in the API doc).
    DEFAULT_PAGESIZE = 1000
    MAX_PAGESIZE = 2000

    # Retry/backoff for transport-level errors and heuristically-transient
    # XML Gateway failures (e.g. the documented single-concurrent-job queueing).
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 2.0  # seconds; doubled after each retry
    RETRIABLE_HTTP_STATUS_CODES = {429, 500, 502, 503, 504}
    # Substrings of an Intacct <description>/<description2> that indicate a
    # transient, retry-worthy condition (concurrency-queue timeout, generic
    # "try again" guidance) rather than a real data/auth/programming error.
    # The doc documents only the *behavior* (queue then error after ~30s), not
    # a specific error code, so this is a conservative heuristic.
    RETRIABLE_ERROR_KEYWORDS = (
        "try your request again",
        "try again",
        "concurrent",
        "busy",
        "please wait",
        "temporarily",
    )

    _DECIMAL = DecimalType(18, 4)


    def _field(name: str, spark_type, nullable: bool = True) -> StructField:
        return StructField(name, spark_type, nullable=nullable)


    CUSTOMER_FIELDS = [
        "RECORDNO",
        "CUSTOMERID",
        "NAME",
        "STATUS",
        "ONETIME",
        "CREDITLIMIT",
        "TAXID",
        "CUSTTYPE",
        "PARENTID",
        "TERMNAME",
        "CURRENCY",
        "ONHOLD",
        "TOTALDUE",
        "WHENCREATED",
        "WHENMODIFIED",
    ]

    VENDOR_FIELDS = [
        "RECORDNO",
        "VENDORID",
        "NAME",
        "STATUS",
        "TOTALDUE",
        "CREDITLIMIT",
        "VENDTYPE",
        "PARENTID",
        "TAXID",
        "CURRENCY",
        "ONHOLD",
        "ONETIME",
        "WHENCREATED",
        "WHENMODIFIED",
    ]

    ARINVOICE_FIELDS = [
        "RECORDNO",
        "CUSTOMERID",
        "CUSTOMERNAME",
        # Live `lookup` on ARINVOICE confirmed the doc's field names here were
        # wrong: INVOICENO/DATECREATED/DATEPOSTED/DATEDUE are not queryable on
        # this object -- a live `query` request fails with "The following
        # fields cannot be queried". The real fields (verified live) are
        # DOCNUMBER (business document number) and WHENPOSTED/WHENDUE, matching
        # the naming convention already used on APBILL.
        "DOCNUMBER",
        "WHENPOSTED",
        "WHENDUE",
        "WHENCREATED",
        "WHENMODIFIED",
        "TOTALENTERED",
        "TOTALPAID",
        "TOTALDUE",
        "TERMNAME",
        "STATE",
        "MODULEKEY",
        "CURRENCY",
    ]

    APBILL_FIELDS = [
        "RECORDNO",
        "VENDORID",
        "RECORDID",
        "WHENCREATED",
        "WHENPOSTED",
        "WHENDUE",
        "WHENMODIFIED",
        "DESCRIPTION",
        "TERMNAME",
        "PAYMENTPRIORITY",
        "ONHOLD",
        "STATE",
        "CURRENCY",
        "BASECURR",
        "EXCHANGE_RATE",
        "MODULEKEY",
    ]

    GLDETAIL_FIELDS = [
        "RECORDNO",
        "GLENTRYKEY",
        "ACCOUNTNO",
        "ACCOUNTTITLE",
        "AMOUNT",
        "DEBITAMOUNT",
        "CREDITAMOUNT",
        "TRX_AMOUNT",
        "TRX_DEBITAMOUNT",
        "TRX_CREDITAMOUNT",
        "BATCH_DATE",
        "BATCH_TITLE",
        "ENTRY_DATE",
        "WHENCREATED",
        "AUWHENCREATED",
        "WHENMODIFIED",
        "BOOKID",
        "MODULEKEY",
        "CLASSID",
        "CLASSNAME",
        "DEPARTMENTID",
        "DEPARTMENTTITLE",
        "LOCATIONID",
        "LOCATIONNAME",
        "PROJECTID",
        "PROJECTNAME",
        "SYMBOL",
        "LINE_NO",
        "DESCRIPTION",
    ]

    TABLE_FIELDS: dict[str, list[str]] = {
        "customers": CUSTOMER_FIELDS,
        "vendors": VENDOR_FIELDS,
        "invoices": ARINVOICE_FIELDS,
        "bills": APBILL_FIELDS,
        "gl_entries": GLDETAIL_FIELDS,
    }

    TABLE_SCHEMAS: dict[str, StructType] = {
        "customers": StructType(
            [
                _field("RECORDNO", LongType(), nullable=False),
                _field("CUSTOMERID", StringType()),
                _field("NAME", StringType()),
                _field("STATUS", StringType()),
                _field("ONETIME", BooleanType()),
                _field("CREDITLIMIT", _DECIMAL),
                _field("TAXID", StringType()),
                _field("CUSTTYPE", StringType()),
                _field("PARENTID", StringType()),
                _field("TERMNAME", StringType()),
                _field("CURRENCY", StringType()),
                _field("ONHOLD", BooleanType()),
                _field("TOTALDUE", _DECIMAL),
                _field("WHENCREATED", DateType()),
                _field("WHENMODIFIED", TimestampType()),
            ]
        ),
        "vendors": StructType(
            [
                _field("RECORDNO", LongType(), nullable=False),
                _field("VENDORID", StringType()),
                _field("NAME", StringType()),
                _field("STATUS", StringType()),
                _field("TOTALDUE", _DECIMAL),
                _field("CREDITLIMIT", _DECIMAL),
                _field("VENDTYPE", StringType()),
                _field("PARENTID", StringType()),
                _field("TAXID", StringType()),
                _field("CURRENCY", StringType()),
                _field("ONHOLD", BooleanType()),
                _field("ONETIME", BooleanType()),
                _field("WHENCREATED", DateType()),
                _field("WHENMODIFIED", TimestampType()),
            ]
        ),
        "invoices": StructType(
            [
                _field("RECORDNO", LongType(), nullable=False),
                _field("CUSTOMERID", StringType()),
                _field("CUSTOMERNAME", StringType()),
                _field("DOCNUMBER", StringType()),
                _field("WHENPOSTED", DateType()),
                _field("WHENDUE", DateType()),
                _field("WHENCREATED", DateType()),
                _field("WHENMODIFIED", TimestampType()),
                _field("TOTALENTERED", _DECIMAL),
                _field("TOTALPAID", _DECIMAL),
                _field("TOTALDUE", _DECIMAL),
                _field("TERMNAME", StringType()),
                _field("STATE", StringType()),
                _field("MODULEKEY", StringType()),
                _field("CURRENCY", StringType()),
            ]
        ),
        "bills": StructType(
            [
                _field("RECORDNO", LongType(), nullable=False),
                _field("VENDORID", StringType()),
                _field("RECORDID", StringType()),
                _field("WHENCREATED", DateType()),
                _field("WHENPOSTED", DateType()),
                _field("WHENDUE", DateType()),
                _field("WHENMODIFIED", TimestampType()),
                _field("DESCRIPTION", StringType()),
                _field("TERMNAME", StringType()),
                _field("PAYMENTPRIORITY", StringType()),
                _field("ONHOLD", BooleanType()),
                _field("STATE", StringType()),
                _field("CURRENCY", StringType()),
                _field("BASECURR", StringType()),
                _field("EXCHANGE_RATE", _DECIMAL),
                _field("MODULEKEY", StringType()),
            ]
        ),
        "gl_entries": StructType(
            [
                # Unlike the other 4 objects, GLDETAIL.RECORDNO is NOT a clean
                # auto-incrementing integer -- live data shows composite string
                # values like "7-35---accrual" (batchkey-entrykey---bookid),
                # consistent with the doc's note that GLDETAIL is "a view, not
                # a table". GLENTRYKEY (confirmed live as a clean integer, e.g.
                # "35") is the real numeric FK back to GLENTRY.RECORDNO.
                _field("RECORDNO", StringType(), nullable=False),
                _field("GLENTRYKEY", LongType()),
                _field("ACCOUNTNO", StringType()),
                _field("ACCOUNTTITLE", StringType()),
                _field("AMOUNT", _DECIMAL),
                _field("DEBITAMOUNT", _DECIMAL),
                _field("CREDITAMOUNT", _DECIMAL),
                _field("TRX_AMOUNT", _DECIMAL),
                _field("TRX_DEBITAMOUNT", _DECIMAL),
                _field("TRX_CREDITAMOUNT", _DECIMAL),
                _field("BATCH_DATE", DateType()),
                _field("BATCH_TITLE", StringType()),
                _field("ENTRY_DATE", DateType()),
                # NOTE: on GLDETAIL, WHENCREATED is *not* a creation timestamp --
                # it's the user-entered transaction date (see doc). Kept as
                # DateType to match that semantic; use AUWHENCREATED for the
                # true record-creation audit timestamp.
                _field("WHENCREATED", DateType()),
                _field("AUWHENCREATED", TimestampType()),
                _field("WHENMODIFIED", TimestampType()),
                _field("BOOKID", StringType()),
                _field("MODULEKEY", StringType()),
                _field("CLASSID", StringType()),
                _field("CLASSNAME", StringType()),
                _field("DEPARTMENTID", StringType()),
                _field("DEPARTMENTTITLE", StringType()),
                _field("LOCATIONID", StringType()),
                _field("LOCATIONNAME", StringType()),
                _field("PROJECTID", StringType()),
                _field("PROJECTNAME", StringType()),
                _field("SYMBOL", StringType()),
                _field("LINE_NO", LongType()),
                _field("DESCRIPTION", StringType()),
            ]
        ),
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/intacct/intacct_xml.py
    ########################################################

    DTD_VERSION = "3.0"

    # Intacct's wire format for date/timestamp fields, e.g. "09/23/2026 00:00:00".
    _INTACCT_DT_FORMAT = "%m/%d/%Y %H:%M:%S"
    _INTACCT_DATE_FORMAT = "%m/%d/%Y"


    class IntacctApiError(RuntimeError):
        """Raised when the XML Gateway returns a failure status."""


    class IntacctSessionExpiredError(IntacctApiError):
        """Raised when the cached session id is no longer valid."""


    def to_intacct_timestamp(iso_str: str) -> str:
        """Convert an internal ISO-8601 cursor value to Intacct's wire format."""
        dt = datetime.fromisoformat(iso_str)
        return dt.strftime(_INTACCT_DT_FORMAT)


    def from_intacct_timestamp(value: str) -> str:
        """Convert an Intacct ``WHENMODIFIED``-style value to an ISO-8601 string.

        Intacct returns timestamps as ``mm/dd/yyyy hh:mm:ss``, which does not
        sort lexically. Internally we always keep cursors as ISO-8601 so plain
        string comparison ("did the cursor advance?") remains correct.
        """
        value = (value or "").strip()
        if not value:
            return value
        for fmt in (_INTACCT_DT_FORMAT, _INTACCT_DATE_FORMAT):
            try:
                return datetime.strptime(value, fmt).isoformat()
            except ValueError:
                continue
        # Unrecognized format -- pass through rather than fail the whole batch.
        return value


    def build_login_envelope(
        *,
        sender_id: str,
        sender_password: str,
        control_id: str,
        user_id: str,
        company_id: str,
        user_password: str,
        location_id: str | None,
        function_xml: str,
    ) -> str:
        location_xml = f"<locationid>{escape(location_id)}</locationid>" if location_id else ""
        auth_xml = (
            "<login>"
            f"<userid>{escape(user_id)}</userid>"
            f"<companyid>{escape(company_id)}</companyid>"
            f"<password>{escape(user_password)}</password>"
            f"{location_xml}"
            "</login>"
        )
        return _build_envelope(
            sender_id=sender_id,
            sender_password=sender_password,
            control_id=control_id,
            auth_xml=auth_xml,
            function_xml=function_xml,
        )


    def build_session_envelope(
        *,
        sender_id: str,
        sender_password: str,
        control_id: str,
        session_id: str,
        function_xml: str,
    ) -> str:
        auth_xml = f"<sessionid>{escape(session_id)}</sessionid>"
        return _build_envelope(
            sender_id=sender_id,
            sender_password=sender_password,
            control_id=control_id,
            auth_xml=auth_xml,
            function_xml=function_xml,
        )


    def _build_envelope(
        *,
        sender_id: str,
        sender_password: str,
        control_id: str,
        auth_xml: str,
        function_xml: str,
    ) -> str:
        return (
            '<?xml version="1.0" encoding="UTF-8"?>'
            "<request>"
            "<control>"
            f"<senderid>{escape(sender_id)}</senderid>"
            f"<password>{escape(sender_password)}</password>"
            f"<controlid>{escape(control_id)}</controlid>"
            "<uniqueid>false</uniqueid>"
            f"<dtdversion>{DTD_VERSION}</dtdversion>"
            "<includewhitespace>false</includewhitespace>"
            "</control>"
            "<operation>"
            f"<authentication>{auth_xml}</authentication>"
            "<content>"
            f'<function controlid="{escape(control_id)}_fn">{function_xml}</function>'
            "</content>"
            "</operation>"
            "</request>"
        )


    def get_api_session_function_xml() -> str:
        return "<getAPISession/>"


    def query_function_xml(
        *,
        object_name: str,
        fields: list[str],
        filter_xml: str,
        pagesize: int,
        offset: int,
    ) -> str:
        select_xml = "".join(f"<field>{escape(f)}</field>" for f in fields)
        return (
            "<query>"
            f"<object>{escape(object_name)}</object>"
            f"<select>{select_xml}</select>"
            f"{filter_xml}"
            "<orderby><order><field>WHENMODIFIED</field><ascending/></order></orderby>"
            f"<pagesize>{pagesize}</pagesize>"
            f"<offset>{offset}</offset>"
            "</query>"
        )


    def range_filter_xml(field: str, since: str | None, until: str | None) -> str:
        """Build a ``<filter>`` block bounding ``field`` by [since, until)."""
        conditions = []
        if since:
            conditions.append(
                f"<greaterthanorequalto><field>{escape(field)}</field>"
                f"<value>{escape(since)}</value></greaterthanorequalto>"
            )
        if until:
            conditions.append(
                f"<lessthan><field>{escape(field)}</field>"
                f"<value>{escape(until)}</value></lessthan>"
            )
        if not conditions:
            return ""
        if len(conditions) == 1:
            return f"<filter>{conditions[0]}</filter>"
        return f"<filter><and>{''.join(conditions)}</and></filter>"


    def parse_response(xml_text: str) -> dict:
        """Parse a response envelope into a small, function-agnostic dict.

        Returns a dict with keys:
            status: "success" | "failure"
            auth_status: "success" | "failure" | None
            error_message: str | None (joined description text, on failure)
            session_id: str | None (only present for getAPISession)
            session_endpoint: str | None
            records: list[dict] (flat field-name -> text, only for query/readMore)
            count / totalcount / numremaining: int (only for query/readMore)
            result_id: str | None
        """
        root = ET.fromstring(xml_text)

        auth_status_el = root.find("./operation/authentication/status")
        auth_status = auth_status_el.text if auth_status_el is not None else None

        result_el = root.find("./operation/result")
        if result_el is None:
            # Authentication itself failed before any function ran.
            return {
                "status": "failure",
                "auth_status": auth_status or "failure",
                "error_message": _extract_error(root),
                "session_id": None,
                "session_endpoint": None,
                "records": [],
                "count": 0,
                "totalcount": 0,
                "numremaining": 0,
                "result_id": None,
            }

        status_el = result_el.find("./status")
        status = status_el.text if status_el is not None else "failure"

        parsed = {
            "status": status,
            "auth_status": auth_status,
            "error_message": None,
            "session_id": None,
            "session_endpoint": None,
            "records": [],
            "count": 0,
            "totalcount": 0,
            "numremaining": 0,
            "result_id": None,
        }

        if status != "success":
            parsed["error_message"] = _extract_error(result_el)
            return parsed

        data_el = result_el.find("./data")
        if data_el is None:
            return parsed

        # getAPISession shape: <data><api><sessionid/><endpoint/></api></data>
        api_el = data_el.find("./api")
        if api_el is not None:
            sid = api_el.find("./sessionid")
            endpoint = api_el.find("./endpoint")
            parsed["session_id"] = sid.text if sid is not None else None
            parsed["session_endpoint"] = endpoint.text if endpoint is not None else None
            return parsed

        # query/readMore shape: <data listtype="OBJ" count="N" totalcount="M"
        #   numremaining="K" resultId="...">child records</data>
        parsed["count"] = int(data_el.get("count", "0") or "0")
        parsed["totalcount"] = int(data_el.get("totalcount", "0") or "0")
        parsed["numremaining"] = int(data_el.get("numremaining", "0") or "0")
        parsed["result_id"] = data_el.get("resultId")

        records = []
        for record_el in list(data_el):
            record = {child.tag: child.text for child in list(record_el)}
            records.append(record)
        parsed["records"] = records

        return parsed


    def _extract_error(el: ET.Element) -> str:
        error_tags = ("description", "description2", "correction")
        parts = [t.text for t in el.iter() if t.tag in error_tags and t.text]
        if parts:
            return " | ".join(parts)
        err = el.find(".//error")
        if err is not None and err.text:
            return err.text
        return "Unknown Intacct API error"


    ########################################################
    # src/databricks/labs/community_connector/sources/intacct/intacct.py
    ########################################################

    DEFAULT_XMLGW_URL = "https://api.intacct.com/ia/xml/xmlgw.phtml"


    class IntacctLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for Sage Intacct (XML Gateway)."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._sender_id = options["sender_id"]
            self._sender_password = options["sender_password"]
            self._company_id = options["company_id"]
            self._user_id = options["user_id"]
            self._user_password = options["user_password"]
            self._location_id = options.get("location_id") or None
            self._base_url = options.get("base_url", DEFAULT_XMLGW_URL)

            # Session cache -- obtained lazily via getAPISession and reused
            # across calls, per the doc's recommended auth flow. Refreshed
            # transparently on session-expiry.
            self._session_id: str | None = None
            self._session_endpoint: str | None = None
            self._control_seq = 0

            # Cap cursors at init time so a trigger never chases continuously
            # arriving GL/AR/AP activity. The next trigger run creates a fresh
            # connector instance with a newer cap.
            self._init_ts = datetime.now(timezone.utc).isoformat()

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(TABLE_TO_OBJECT.keys())

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            # TODO: the doc recommends calling `lookup` per-object at connector
            # init to discover tenant-specific custom fields; this hard-codes
            # the documented core fields instead (see intacct_schemas.py). A
            # follow-up could merge `lookup`'s field list on top of this base
            # schema for full custom-field fidelity.
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            # All 5 objects: WHENMODIFIED-based CDC, no delete-tombstone feed
            # documented (deactivation/void+reversal show up as WHENMODIFIED
            # bumps, not deletes) -- see "Object's ingestion type" in the doc.
            return {
                "primary_keys": [PRIMARY_KEY_FIELD],
                "cursor_field": CURSOR_FIELD,
                "ingestion_type": "cdc",
            }

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            return self._read_incremental_by_window(table_name, start_offset or {}, table_options)

        # ------------------------------------------------------------------
        # Incremental read (Strategy A -- sliding time-window)
        # ------------------------------------------------------------------

        def _read_incremental_by_window(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            object_name = TABLE_TO_OBJECT[table_name]
            fields = TABLE_FIELDS[table_name]

            since = start_offset.get("cursor")
            if not since:
                since = table_options.get("start_timestamp")
            if not since:
                since = self._peek_oldest_cursor(object_name)
            if not since:
                # No records exist yet for this object -- nothing to read.
                return iter([]), start_offset or {}

            # Already caught up to init time -- skip the API call entirely.
            if since >= self._init_ts:
                return iter([]), start_offset if start_offset else {}

            window_seconds = int(table_options.get("window_seconds", "86400"))
            max_records = int(table_options.get("max_records_per_batch", str(MAX_PAGESIZE)))
            pagesize = min(
                int(table_options.get("pagesize", str(DEFAULT_PAGESIZE))), MAX_PAGESIZE
            )

            window_end_dt = datetime.fromisoformat(since) + timedelta(seconds=window_seconds)
            window_end = min(window_end_dt.isoformat(), self._init_ts)

            records: list[dict] = []
            offset = 0
            window_drained = False
            while len(records) < max_records:
                parsed = self._query(object_name, fields, since, window_end, pagesize, offset)
                batch = parsed.get("records") or []
                if not batch:
                    window_drained = True
                    break

                records.extend(_normalize_record(table_name, r) for r in batch)
                offset += len(batch)

                if parsed.get("numremaining", 0) <= 0:
                    window_drained = True
                    break

            # When the window is fully drained, advance the cursor to
            # window_end rather than the last record's cursor -- otherwise a
            # follow-up call would re-scan the (now empty) tail of the window
            # and return the same offset it started with, breaking
            # Trigger.AvailableNow convergence.
            if window_drained:
                end_offset = {"cursor": window_end}
            else:
                # max_records cap hit mid-window. Safe to resume from the last
                # processed record's cursor: this table is `cdc` (has a primary
                # key), so any re-fetched overlap on the next call is deduped
                # by upsert.
                end_offset = {"cursor": records[-1][CURSOR_FIELD]}

            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        def _peek_oldest_cursor(self, object_name: str) -> str | None:
            """Auto-discover the oldest record's cursor to bound the first call.

            Requests a single record ordered ascending by WHENMODIFIED with no
            filter -- the first (and only) record returned is the oldest.
            """
            function_xml = query_function_xml(
                object_name=object_name,
                fields=[CURSOR_FIELD],
                filter_xml="",
                pagesize=1,
                offset=0,
            )
            parsed = self._call_function(function_xml, "peek")
            records = parsed.get("records") or []
            if not records:
                return None
            raw = records[0].get(CURSOR_FIELD)
            return from_intacct_timestamp(raw) if raw else None

        def _query(
            self,
            object_name: str,
            fields: list[str],
            since_iso: str,
            until_iso: str,
            pagesize: int,
            offset: int,
        ) -> dict:
            filter_xml = range_filter_xml(
                CURSOR_FIELD,
                to_intacct_timestamp(since_iso) if since_iso else None,
                to_intacct_timestamp(until_iso) if until_iso else None,
            )
            function_xml = query_function_xml(
                object_name=object_name,
                fields=fields,
                filter_xml=filter_xml,
                pagesize=pagesize,
                offset=offset,
            )
            return self._call_function(function_xml, "query")

        # ------------------------------------------------------------------
        # XML Gateway plumbing -- session management, request/retry
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_TO_OBJECT:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {list(TABLE_TO_OBJECT)}"
                )

        def _next_control_id(self, prefix: str) -> str:
            self._control_seq += 1
            return f"{prefix}_{self._control_seq}"

        def _ensure_session(self) -> None:
            if self._session_id:
                return
            control_id = self._next_control_id("get_session")
            envelope = build_login_envelope(
                sender_id=self._sender_id,
                sender_password=self._sender_password,
                control_id=control_id,
                user_id=self._user_id,
                company_id=self._company_id,
                user_password=self._user_password,
                location_id=self._location_id,
                function_xml=get_api_session_function_xml(),
            )
            parsed = self._post(self._base_url, envelope, expect_session=True)
            if not parsed.get("session_id"):
                raise RuntimeError(
                    f"Failed to obtain Intacct API session: {parsed.get('error_message')}"
                )
            self._session_id = parsed["session_id"]
            self._session_endpoint = parsed.get("session_endpoint") or self._base_url

        def _call_function(self, function_xml: str, control_prefix: str) -> dict:
            self._ensure_session()
            control_id = self._next_control_id(control_prefix)
            envelope = build_session_envelope(
                sender_id=self._sender_id,
                sender_password=self._sender_password,
                control_id=control_id,
                session_id=self._session_id,
                function_xml=function_xml,
            )
            try:
                return self._post(self._session_endpoint or self._base_url, envelope)
            except IntacctSessionExpiredError:
                # Session died between calls (expiry / server-side eviction).
                # Refresh once and retry the same function.
                self._session_id = None
                self._ensure_session()
                control_id = self._next_control_id(control_prefix)
                envelope = build_session_envelope(
                    sender_id=self._sender_id,
                    sender_password=self._sender_password,
                    control_id=control_id,
                    session_id=self._session_id,
                    function_xml=function_xml,
                )
                return self._post(self._session_endpoint or self._base_url, envelope)

        def _post(self, url: str, envelope: str, expect_session: bool = False) -> dict:
            """POST one XML envelope, retrying on transport and transient API errors.

            Retries (with exponential backoff) on:
              - Retriable HTTP status codes (429/5xx).
              - XML Gateway failures whose error text matches a transient-error
                heuristic (the doc documents queueing/backoff *behavior* for
                the 1-concurrent-job limit, but not a specific error code, so
                this is a conservative keyword match rather than an exact code).
            Raises ``IntacctSessionExpiredError`` (not retried here -- handled
            by the caller, which refreshes the session) when a session-based
            call's authentication block reports failure.
            """
            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                resp = requests.post(
                    url,
                    data=envelope.encode("utf-8"),
                    headers={"Content-Type": "application/xml"},
                    timeout=30,
                )

                if resp.status_code in RETRIABLE_HTTP_STATUS_CODES:
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(backoff)
                        backoff *= 2
                        continue
                    resp.raise_for_status()

                if resp.status_code != 200:
                    raise RuntimeError(f"Intacct API HTTP {resp.status_code}: {resp.text[:500]}")

                parsed = parse_response(resp.text)
                if parsed["status"] == "success":
                    return parsed

                if not expect_session and parsed.get("auth_status") == "failure":
                    raise IntacctSessionExpiredError(
                        parsed.get("error_message") or "Intacct session expired"
                    )

                message = (parsed.get("error_message") or "").lower()
                if attempt < MAX_RETRIES - 1 and any(k in message for k in RETRIABLE_ERROR_KEYWORDS):
                    time.sleep(backoff)
                    backoff *= 2
                    continue

                raise IntacctApiError(parsed.get("error_message") or "Intacct API request failed")

            raise RuntimeError("Intacct API request failed after exhausting retries")


    def _normalize_record(table_name: str, raw: dict) -> dict:
        """Convert Intacct's wire formats to framework-castable values.

        Intacct dates/timestamps are ``mm/dd/yyyy`` / ``mm/dd/yyyy hh:mm:ss``,
        which Spark's default string->Date/Timestamp cast does not parse.
        Values are rewritten to ISO-8601 here; other fields (numeric/string)
        are passed through as raw text and left for the framework's schema-
        driven type coercion (per the "do not pre-convert JSON" rule). Fields
        absent from the response (Intacct omits some empty fields) are
        explicitly set to ``None`` rather than left as an empty dict.
        """
        schema = TABLE_SCHEMAS[table_name]
        normalized: dict = {}
        for f in schema.fields:
            value = raw.get(f.name)
            if value is not None:
                if isinstance(f.dataType, TimestampType):
                    value = from_intacct_timestamp(value)
                elif isinstance(f.dataType, DateType):
                    value = from_intacct_timestamp(value)[:10]
                elif isinstance(f.dataType, BooleanType):
                    value = str(value).strip().lower() in ("true", "t", "1", "yes")
            normalized[f.name] = value
        return normalized


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = IntacctLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
