# ==============================================================================
# Merged Lakeflow Source: miter
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import math
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/miter/miter_schemas.py
    ########################################################

    DEFAULT_BASE_URL = "https://api.miter.com/api/v2"

    REQUEST_TIMEOUT = 60
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 2.0
    RETRIABLE_STATUS_CODES = (429, 500, 502, 503, 504)

    # ``limit`` accepts 1-1000, default 100 (OpenAPI spec).
    DEFAULT_PAGE_SIZE = 100
    MAX_PAGE_SIZE = 1000

    DEFAULT_MAX_RECORDS_PER_BATCH = 5000
    DEFAULT_WINDOW_SECONDS = 86400
    DEFAULT_MAX_PARTITIONS = 200
    DEFAULT_PARENTS_PER_PARTITION = 20

    # Every object in this API exposes ``updated_at`` and supports
    # ``sort[field]=updated_at`` with ``after_exclusive``/``before_inclusive``.
    CURSOR_FIELD = "updated_at"
    PRIMARY_KEY = "id"

    # --------------------------------------------------------------------------
    # Endpoints
    # --------------------------------------------------------------------------

    LEDGER_LINE_ITEMS = "ledger_line_items"

    # ``parent_table`` marks a nested resource: it has no global list endpoint
    # and must be read once per parent record's id.
    TABLE_ENDPOINTS = {
        "ledger_accounts": {"path": "/ledger_accounts"},
        "ledger_entries": {"path": "/ledger_entries"},
        LEDGER_LINE_ITEMS: {
            "path": "/ledger_entries/{parent_id}/line_items",
            "parent_table": "ledger_entries",
        },
        "ledger_mappings": {"path": "/ledger_mappings"},
    }

    SUPPORTED_TABLES = tuple(TABLE_ENDPOINTS)

    # --------------------------------------------------------------------------
    # Schemas
    # --------------------------------------------------------------------------

    _LEDGER_ACCOUNTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
            StructField("custom_id", StringType(), True),
            StructField("label", StringType(), True),
            StructField("classification", StringType(), True),
            StructField("parent_account_id", StringType(), True),
            StructField("status", StringType(), True),
            StructField("is_selectable_by_team_members", BooleanType(), True),
        ]
    )

    _LEDGER_ENTRY_SOURCE_OBJECTS = StructType(
        [
            StructField("payroll_id", StringType(), True),
            StructField("check_payment_id", StringType(), True),
            StructField("recoded_timesheet_ids", ArrayType(StringType()), True),
            StructField("reimbursement_id", StringType(), True),
            StructField("reimbursement_ids", ArrayType(StringType()), True),
            StructField("expense_id", StringType(), True),
            StructField("stripe_inbound_transfer_id", StringType(), True),
            StructField("bill_ids", ArrayType(StringType()), True),
            StructField("equipment_timesheet_ids", ArrayType(StringType()), True),
        ]
    )

    _LEDGER_ENTRIES_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
            StructField("ledger_id", StringType(), True),
            StructField("entry_type", StringType(), True),
            StructField("posted_at", TimestampType(), True),
            StructField("description", StringType(), True),
            StructField("company_entity_id", StringType(), True),
            StructField("source_objects", _LEDGER_ENTRY_SOURCE_OBJECTS, True),
        ]
    )

    # ``ReferenceCustomFieldValue.value`` is ``anyOf`` string/number/boolean/
    # array, so it is normalised to a string (JSON-encoded when non-scalar)
    # before being handed to Spark.
    _CUSTOM_FIELD_VALUE = StructType(
        [
            StructField("custom_field_id", StringType(), True),
            StructField("value", StringType(), True),
        ]
    )

    _LEDGER_LINE_ITEMS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
            StructField("ledger_entry_id", StringType(), True),
            StructField("account_type", StringType(), True),
            StructField("miter_type", StringType(), True),
            StructField("direction", StringType(), True),
            StructField("amount", DoubleType(), True),
            StructField("ledger_account_id", StringType(), True),
            StructField("description", StringType(), True),
            StructField("payroll_id", StringType(), True),
            StructField("voided_payroll_id", StringType(), True),
            StructField("payday", DateType(), True),
            StructField("team_member_id", StringType(), True),
            StructField("employment_type", StringType(), True),
            StructField("department_id", StringType(), True),
            StructField("location_id", StringType(), True),
            StructField("class_id", StringType(), True),
            StructField("company_entity_id", StringType(), True),
            StructField("job_id", StringType(), True),
            StructField("activity_id", StringType(), True),
            StructField("work_order_id", StringType(), True),
            StructField("workers_compensation_code_id", StringType(), True),
            StructField("timesheet_id", StringType(), True),
            StructField("equipment_timesheet_id", StringType(), True),
            StructField("equipment_id", StringType(), True),
            StructField("reimbursement_id", StringType(), True),
            StructField("reimbursement_date", DateType(), True),
            StructField("accrual_date", DateType(), True),
            StructField("classification_id", StringType(), True),
            StructField("pay_rate_group_id", StringType(), True),
            StructField("fringe_classification_id", StringType(), True),
            StructField("fringe_pay_rate_group_id", StringType(), True),
            StructField("burden_rate_id", StringType(), True),
            StructField("earning_type", StringType(), True),
            StructField("earning_date", DateType(), True),
            StructField("benefit_type", StringType(), True),
            StructField("hours", DoubleType(), True),
            StructField("void", BooleanType(), True),
            StructField("memo", StringType(), True),
            StructField("cost_type_id", StringType(), True),
            StructField("custom_earning_code_id", StringType(), True),
            StructField("custom_field_values", ArrayType(_CUSTOM_FIELD_VALUE), True),
            StructField("recoded", BooleanType(), True),
            StructField("manually_edited", BooleanType(), True),
        ]
    )

    # ``defaults`` / ``*_accounts`` are open-keyed objects whose values are
    # nullable ledger-account ids — a map, not a fixed struct.
    _LEDGER_MAPPINGS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("created_at", TimestampType(), True),
            StructField("updated_at", TimestampType(), True),
            StructField("name", StringType(), True),
            StructField("is_company_default", BooleanType(), True),
            StructField("defaults", MapType(StringType(), StringType()), True),
            StructField(
                "earning_type_accounts", MapType(StringType(), StringType()), True
            ),
            StructField(
                "benefit_type_expense_accounts",
                MapType(StringType(), StringType()),
                True,
            ),
            StructField(
                "benefit_type_liability_accounts",
                MapType(StringType(), StringType()),
                True,
            ),
        ]
    )

    TABLE_SCHEMAS = {
        "ledger_accounts": _LEDGER_ACCOUNTS_SCHEMA,
        "ledger_entries": _LEDGER_ENTRIES_SCHEMA,
        LEDGER_LINE_ITEMS: _LEDGER_LINE_ITEMS_SCHEMA,
        "ledger_mappings": _LEDGER_MAPPINGS_SCHEMA,
    }

    # --------------------------------------------------------------------------
    # Metadata
    # --------------------------------------------------------------------------

    # No object in the Miter API supports delete detection (no tombstones, no
    # soft-delete field, no audit-log endpoint), so every table is plain ``cdc``.
    TABLE_METADATA = {
        table: {
            "primary_keys": [PRIMARY_KEY],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        }
        for table in SUPPORTED_TABLES
    }

    # Struct-typed fields that the API may return as ``{}``; Spark requires
    # ``None`` instead of an empty struct.
    STRUCT_FIELDS = {
        "ledger_entries": ("source_objects",),
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/miter/miter.py
    ########################################################

    def _now_iso() -> str:
        return _to_iso(datetime.now(timezone.utc))


    def _to_iso(value: datetime) -> str:
        """Canonical Miter datetime: millisecond precision, ``Z`` suffix."""
        return value.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


    def _parse_iso(value: str) -> datetime:
        """Parse an ISO-8601 timestamp; naive values are treated as UTC.

        Cursors arrive in several shapes (API values with or without
        milliseconds, user-supplied option strings, canonical values this
        connector emits), so ordering is always decided on parsed datetimes
        rather than on the raw strings.
        """
        text = value.strip()
        if text.endswith(("Z", "z")):
            text = text[:-1] + "+00:00"
        parsed = datetime.fromisoformat(text)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed


    def _scalar_to_str(value: Any) -> Any:
        """Flatten a polymorphic custom-field value to a string."""
        if value is None or isinstance(value, str):
            return value
        return json.dumps(value, ensure_ascii=False)


    class MiterLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for the Miter v2 REST API.

        Connection options:
            api_token   Miter API token, sent as ``Authorization: Bearer``.
            base_url    Optional API root. Defaults to the production URL
                        ``https://api.miter.com/api/v2``; point it at
                        ``https://api.staging.miter.com/api/v2`` when using a
                        staging token.

        Per-table options:
            page_size               API ``limit`` per request (default 100, max 1000).
            window_seconds          Partition / microbatch width in seconds (default 86400).
            max_partitions          Upper bound on partitions per microbatch (default 200).
            max_records_per_batch   Cap on records returned by one ``read_table`` call.
            start_timestamp         Lower bound for the very first read.
            lookback_seconds        Seconds subtracted from the start cursor at query time.
            max_pages               Safety cap on pages per paginated call (0 = unlimited).
            parent_ids              ledger_line_items only: comma-separated parent
                                    ledger-entry ids to restrict the sync to.
            max_parents             ledger_line_items only: cap on parents (0 = unlimited).
            parents_per_partition   ledger_line_items only: parents per partition (default 20).
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            api_token = options.get("api_token")
            if not api_token:
                raise ValueError("Miter connector requires connection option 'api_token'")
            self._api_token = api_token
            self._base_url = (options.get("base_url") or DEFAULT_BASE_URL).rstrip("/")

            # Cap every offset at construction time so Trigger.AvailableNow
            # converges instead of chasing rows written while the run is in
            # flight. The next trigger builds a fresh instance with a newer cap.
            self._init_time = _now_iso()

        # ------------------------------------------------------------------
        # LakeflowConnect — discovery
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        # ------------------------------------------------------------------
        # SupportsPartitionedStream
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            return table_name in SUPPORTED_TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """High-water mark for the table, capped at the connector's init time.

            Metadata-only: the cap is a wall-clock snapshot, so no API call is
            needed. Returning a constant also guarantees the second call of a
            trigger matches the first, which is how Trigger.AvailableNow stops.
            """
            self._validate_table(table_name)
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split the ``(start, end]`` updated_at range into parallel units."""
            self._validate_table(table_name)

            if start_offset is None and end_offset is None:
                since = table_options.get("start_timestamp")
                until = self._init_time
            else:
                since = (start_offset or {}).get("cursor") or table_options.get(
                    "start_timestamp"
                )
                until = (end_offset or {}).get("cursor") or self._init_time

            until_dt = _parse_iso(until)
            if since is not None and _parse_iso(since) >= until_dt:
                return []

            since = self._apply_lookback(since, table_options)

            if table_name == LEDGER_LINE_ITEMS:
                return self._parent_partitions(table_options, since, until)

            if since is None:
                since = self._discover_oldest_cursor(table_name, table_options)
            if since is None:
                # Empty table, or the peek failed — one unbounded partition.
                return [{"until": until}]

            return self._window_partitions(since, until, table_options)

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read one partition on an executor."""
            self._validate_table(table_name)
            since = partition.get("since")
            until = partition.get("until")

            if table_name == LEDGER_LINE_ITEMS:
                for parent_id in partition.get("parent_ids") or []:
                    yield from self._read_line_items(parent_id, since, until, table_options)
                return

            path = TABLE_ENDPOINTS[table_name]["path"]
            params = self._list_params(since, until, table_options)
            for record in self._paginate(path, params, table_options):
                yield self._normalize(table_name, record)

        # ------------------------------------------------------------------
        # LakeflowConnect — single-driver fallback read
        # ------------------------------------------------------------------

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Sequential sliding-window read, used when partitioning is off.

            Each call drains one ``window_seconds`` slice of the cursor range and
            advances the offset to the window end, so the offset converges on the
            init-time cap and the trigger terminates.
            """
            self._validate_table(table_name)
            start_offset = start_offset or {}

            since = start_offset.get("cursor") or table_options.get("start_timestamp")
            if since is None and table_name != LEDGER_LINE_ITEMS:
                since = self._discover_oldest_cursor(table_name, table_options)

            if since is not None and _parse_iso(since) >= _parse_iso(self._init_time):
                return iter([]), start_offset or {"cursor": self._init_time}

            if since is None:
                # No lower bound available: read the whole history in one batch.
                window_end = self._init_time
            else:
                window_seconds = self._int_option(
                    table_options, "window_seconds", DEFAULT_WINDOW_SECONDS, minimum=1
                )
                window_end_dt = _parse_iso(since) + timedelta(seconds=window_seconds)
                window_end = min(_to_iso(window_end_dt), self._init_time, key=_parse_iso)

            query_since = self._apply_lookback(since, table_options)

            # ledger_line_items fans out over parents, so a partial window would
            # strand the parents not yet visited. The window must be drained;
            # window_seconds governs the batch size instead of the record cap.
            max_records = (
                None
                if table_name == LEDGER_LINE_ITEMS
                else self._int_option(
                    table_options,
                    "max_records_per_batch",
                    DEFAULT_MAX_RECORDS_PER_BATCH,
                    minimum=1,
                )
            )

            records: list[dict] = []
            drained = True
            for record in self._iter_window(
                table_name, query_since, window_end, table_options
            ):
                records.append(record)
                if max_records is None or len(records) < max_records:
                    continue
                # Only stop early once the cursor has moved past the incoming
                # offset; otherwise (with a lookback in play) the next call would
                # resume at or before where this one started and never progress.
                if since is None or _parse_iso(record[CURSOR_FIELD]) > _parse_iso(since):
                    drained = False
                    break

            if drained and not records and table_name != LEDGER_LINE_ITEMS:
                # Empty window: skip ahead to the next row that actually exists
                # instead of stepping through every intervening window.
                end_offset = {
                    "cursor": self._next_data_cursor(table_name, window_end, table_options)
                }
            elif drained:
                end_offset = {"cursor": window_end}
            else:
                # ``after_exclusive`` guarantees every record's cursor is strictly
                # greater than ``since``, so resuming here always makes progress.
                end_offset = {"cursor": records[-1][CURSOR_FIELD]}

            if start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        # ------------------------------------------------------------------
        # Partition planning
        # ------------------------------------------------------------------

        def _window_partitions(
            self, since: str, until: str, table_options: dict[str, str]
        ) -> list[dict]:
            window_seconds = self._int_option(
                table_options, "window_seconds", DEFAULT_WINDOW_SECONDS, minimum=1
            )
            max_partitions = self._int_option(
                table_options, "max_partitions", DEFAULT_MAX_PARTITIONS, minimum=1
            )

            since_dt = _parse_iso(since)
            until_dt = _parse_iso(until)
            total_seconds = (until_dt - since_dt).total_seconds()
            if total_seconds <= 0:
                return []

            count = math.ceil(total_seconds / window_seconds)
            if count > max_partitions:
                window_seconds = math.ceil(total_seconds / max_partitions)

            partitions: list[dict] = []
            cursor_dt = since_dt
            while cursor_dt < until_dt:
                next_dt = min(cursor_dt + timedelta(seconds=window_seconds), until_dt)
                partitions.append(
                    {"since": _to_iso(cursor_dt), "until": _to_iso(next_dt)}
                )
                cursor_dt = next_dt
            # The final boundary must match the requested end exactly so the
            # committed offset and the data read stay in step.
            if partitions:
                partitions[-1]["until"] = until
            return partitions

        def _parent_partitions(
            self, table_options: dict[str, str], since: str | None, until: str
        ) -> list[dict]:
            parent_ids = self._resolve_parent_ids(table_options)
            if not parent_ids:
                return []

            chunk = self._int_option(
                table_options,
                "parents_per_partition",
                DEFAULT_PARENTS_PER_PARTITION,
                minimum=1,
            )
            partitions: list[dict] = []
            for start in range(0, len(parent_ids), chunk):
                partition: dict = {
                    "parent_ids": parent_ids[start : start + chunk],
                    "until": until,
                }
                if since is not None:
                    partition["since"] = since
                partitions.append(partition)
            return partitions

        def _resolve_parent_ids(self, table_options: dict[str, str]) -> list[str]:
            """Parent ledger-entry ids to fan the nested read out over.

            Parents are listed unbounded by the child's cursor: a line item can be
            updated long after its parent entry was, so restricting parents to the
            current window would silently drop those children.
            """
            configured = table_options.get("parent_ids")
            if configured:
                ids = [pid.strip() for pid in configured.split(",") if pid.strip()]
            else:
                parent_table = TABLE_ENDPOINTS[LEDGER_LINE_ITEMS]["parent_table"]
                params = self._list_params(None, None, table_options)
                params["output_fields"] = "id"
                ids = [
                    record["id"]
                    for record in self._paginate(
                        TABLE_ENDPOINTS[parent_table]["path"], params, table_options
                    )
                    if record.get("id")
                ]

            max_parents = self._int_option(table_options, "max_parents", 0, minimum=0)
            if max_parents:
                ids = ids[:max_parents]
            return ids

        def _discover_oldest_cursor(
            self, table_name: str, table_options: dict[str, str]
        ) -> str | None:
            """Peek at the oldest row so the first read has a bounded lower edge.

            The API sorts ascending on request, so a single one-row page returns
            the oldest record. One second is subtracted because the resulting
            value is used as an *exclusive* lower bound.
            """
            params = {
                "sort[field]": CURSOR_FIELD,
                "sort[direction]": "ascending",
                "limit": "1",
                "output_fields": CURSOR_FIELD,
            }
            body = self._get(TABLE_ENDPOINTS[table_name]["path"], params)
            results = (body.get("data") or {}).get("results") or []
            if not results:
                return None
            oldest = results[0].get(CURSOR_FIELD)
            if not oldest:
                return None
            return _to_iso(_parse_iso(oldest) - timedelta(seconds=1))

        def _next_data_cursor(
            self, table_name: str, after: str, table_options: dict[str, str]
        ) -> str:
            """Cursor just before the oldest row newer than ``after``.

            Used to collapse long empty stretches in the sequential read path.
            Falls back to the init-time cap when nothing newer exists, which is
            what makes ``read_table`` converge in a bounded number of calls.
            """
            params = {
                "sort[field]": CURSOR_FIELD,
                "sort[direction]": "ascending",
                "sort[after_exclusive]": after,
                "sort[before_inclusive]": self._init_time,
                "limit": "1",
                "output_fields": CURSOR_FIELD,
            }
            body = self._get(TABLE_ENDPOINTS[table_name]["path"], params)
            results = (body.get("data") or {}).get("results") or []
            next_value = results[0].get(CURSOR_FIELD) if results else None
            if not next_value:
                return self._init_time
            candidate = _to_iso(_parse_iso(next_value) - timedelta(seconds=1))
            return max(candidate, after, key=_parse_iso)

        def _apply_lookback(
            self, since: str | None, table_options: dict[str, str]
        ) -> str | None:
            lookback = self._int_option(table_options, "lookback_seconds", 0, minimum=0)
            if since is None or lookback <= 0:
                return since
            return _to_iso(_parse_iso(since) - timedelta(seconds=lookback))

        # ------------------------------------------------------------------
        # Reading
        # ------------------------------------------------------------------

        def _iter_window(
            self,
            table_name: str,
            since: str | None,
            until: str,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            if table_name == LEDGER_LINE_ITEMS:
                for parent_id in self._resolve_parent_ids(table_options):
                    yield from self._read_line_items(
                        parent_id, since, until, table_options
                    )
                return

            params = self._list_params(since, until, table_options)
            for record in self._paginate(
                TABLE_ENDPOINTS[table_name]["path"], params, table_options
            ):
                yield self._normalize(table_name, record)

        def _read_line_items(
            self,
            parent_id: str,
            since: str | None,
            until: str | None,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            path = TABLE_ENDPOINTS[LEDGER_LINE_ITEMS]["path"].format(parent_id=parent_id)
            params = self._list_params(since, until, table_options)
            for record in self._paginate(path, params, table_options):
                yield self._normalize(LEDGER_LINE_ITEMS, record)

        def _list_params(
            self,
            since: str | None,
            until: str | None,
            table_options: dict[str, str],
        ) -> dict[str, str]:
            params = {
                "sort[field]": CURSOR_FIELD,
                "sort[direction]": "ascending",
                "limit": str(self._page_size(table_options)),
            }
            if since:
                params["sort[after_exclusive]"] = since
            if until:
                params["sort[before_inclusive]"] = until
            return params

        def _paginate(
            self, path: str, params: dict[str, str], table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Walk the opaque ``data.next_page`` cursor until it goes null."""
            max_pages = self._int_option(table_options, "max_pages", 0, minimum=0)
            query = dict(params)
            seen_cursors: set[str] = set()
            pages = 0

            while True:
                body = self._get(path, query)
                data = body.get("data") or {}
                yield from data.get("results") or []

                pages += 1
                if max_pages and pages >= max_pages:
                    return

                next_page = data.get("next_page")
                # A repeated cursor would loop forever; treat it as the end.
                if not next_page or next_page in seen_cursors:
                    return
                seen_cursors.add(next_page)
                query["page"] = next_page

        def _get(self, path: str, params: dict[str, str]) -> dict:
            url = f"{self._base_url}{path}"
            headers = {
                "Authorization": f"Bearer {self._api_token}",
                "Accept": "application/json",
            }

            backoff = INITIAL_BACKOFF
            response = None
            for attempt in range(MAX_RETRIES):
                response = self._session().get(
                    url, headers=headers, params=params, timeout=REQUEST_TIMEOUT
                )
                if response.status_code not in RETRIABLE_STATUS_CODES:
                    break
                if attempt < MAX_RETRIES - 1:
                    time.sleep(self._retry_delay(response, backoff))
                    backoff *= 2

            if response.status_code != 200:
                raise RuntimeError(
                    f"Miter API request failed: GET {path} -> "
                    f"{response.status_code} {response.text[:500]}"
                )
            return response.json()

        @staticmethod
        def _retry_delay(response, backoff: float) -> float:
            retry_after = response.headers.get("Retry-After")
            if retry_after:
                try:
                    return max(float(retry_after), 0.0)
                except ValueError:
                    pass
            return backoff

        def _session(self) -> requests.Session:
            session = getattr(self, "_http_session", None)
            if session is None:
                session = requests.Session()
                self._http_session = session
            return session

        def __getstate__(self) -> dict:
            # The HTTP session is not picklable; executors build their own.
            state = dict(self.__dict__)
            state.pop("_http_session", None)
            return state

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        @staticmethod
        def _normalize(table_name: str, record: dict) -> dict:
            for field_name in STRUCT_FIELDS.get(table_name, ()):  # empty struct -> None
                if record.get(field_name) == {}:
                    record[field_name] = None

            if table_name == LEDGER_LINE_ITEMS:
                values = record.get("custom_field_values")
                if isinstance(values, list):
                    record["custom_field_values"] = [
                        {
                            "custom_field_id": item.get("custom_field_id"),
                            "value": _scalar_to_str(item.get("value")),
                        }
                        for item in values
                        if isinstance(item, dict)
                    ]
            return record

        def _page_size(self, table_options: dict[str, str]) -> int:
            size = self._int_option(
                table_options, "page_size", DEFAULT_PAGE_SIZE, minimum=1
            )
            return min(size, MAX_PAGE_SIZE)

        @staticmethod
        def _int_option(
            table_options: dict[str, str], key: str, default: int, *, minimum: int
        ) -> int:
            raw = table_options.get(key)
            if raw is None or raw == "":
                return default
            try:
                return max(int(raw), minimum)
            except (TypeError, ValueError):
                return default

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {list(SUPPORTED_TABLES)}"
                )


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = MiterLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
