# ==============================================================================
# Merged Lakeflow Source: buildops
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Iterator,
    Optional,
    Sequence,
)
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import quote
import base64
import random
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/buildops/buildops_schemas.py
    ########################################################

    DEFAULT_BASE_URL = "https://public-api.dev.buildops.com"
    TOKEN_PATH = "/v1/auth/token"
    BILL_PATH = "/v2/bills/{bill_id}"
    BILLS_PATH = "/v2/bills"

    REQUEST_TIMEOUT_SECONDS = 30
    MAX_RETRIES = 5
    INITIAL_BACKOFF_SECONDS = 1.0
    MAX_BACKOFF_SECONDS = 60.0
    RETRIABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})

    # Refresh the cached token this many seconds before it expires (capped at half
    # the token lifetime for very short-lived tokens).
    TOKEN_REFRESH_MARGIN_SECONDS = 300
    DEFAULT_TOKEN_TTL_SECONDS = 86400

    # ---------------------------------------------------------------------------
    # Table options
    # ---------------------------------------------------------------------------

    # Values accepted by the ``include`` query parameter of GET /v2/bills/{billId}.
    # The live API expects ONE comma-separated value (``include=vendor,job``); the
    # repeated-key form (``include=vendor&include=job``) is silently ignored.
    # Verified live: besides the 12 documented relations, ``billLines``,
    # ``addresses`` and ``vendorDocumentAttachment`` are also include-gated -- GET
    # omits those keys entirely unless they are requested. Unknown values -> 400.
    BILL_INCLUDE_VALUES = (
        "billLines",
        "addresses",
        "vendorDocumentAttachment",
        "purchaseOrder",
        "purchaseOrderReceipt",
        "vendor",
        "job",
        "project",
        "department",
        "orderedBy",
        "projectManager",
        "assignedTo",
        "approvalNoteBy",
        "paymentTerm",
        "taxRate",
    )

    # ---------------------------------------------------------------------------
    # Nested struct types
    # ---------------------------------------------------------------------------

    # AuditInfo. ``createdBy`` / ``lastUpdatedBy`` / ``deletedBy`` reference the
    # undocumented ``UserAuditInfo`` object and are carried as JSON strings.
    AUDIT_INFO_SCHEMA = StructType(
        [
            StructField("createdBy", StringType(), True),
            StructField("createdDate", StringType(), True),
            StructField("createdDateTime", LongType(), True),
            StructField("lastUpdatedBy", StringType(), True),
            StructField("lastUpdatedDate", StringType(), True),
            StructField("lastUpdatedDateTime", LongType(), True),
            StructField("deletedBy", StringType(), True),
            StructField("deletedDate", StringType(), True),
            StructField("deletedDateTime", LongType(), True),
        ]
    )

    # PublicQuantityBilledDto (billLines[].purchaseOrderReceiptLineBillLines[]).
    QUANTITY_BILLED_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("audit", AUDIT_INFO_SCHEMA, True),
            StructField("quantityBilled", DoubleType(), True),
            StructField("purchaseOrderReceiptLineId", StringType(), True),
            StructField("billLineId", StringType(), True),
            StructField("purchaseOrderReceiptLine", StringType(), True),
        ]
    )

    # PublicBillLineDto (billLines[]).
    BILL_LINE_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("tenantId", StringType(), True),
            StructField("audit", AUDIT_INFO_SCHEMA, True),
            StructField("description", StringType(), True),
            StructField("quantity", DoubleType(), True),
            StructField("lineNumber", LongType(), True),
            StructField("unitCost", DoubleType(), True),
            StructField("unitCostWithTax", DoubleType(), True),
            StructField("unitPrice", DoubleType(), True),
            StructField("taxable", BooleanType(), True),
            StructField("markup", DoubleType(), True),
            StructField("itemGlGroupId", StringType(), True),
            StructField("taxRegionId", StringType(), True),
            StructField("taxCategoryId", StringType(), True),
            StructField("amount", DoubleType(), True),
            StructField("taxAmount", DoubleType(), True),
            StructField("useTaxAmount", DoubleType(), True),
            StructField("totalAmount", DoubleType(), True),
            StructField("accountingSystemLineId", StringType(), True),
            StructField("billId", StringType(), True),
            StructField("purchaseOrderLineId", StringType(), True),
            StructField("purchaseOrderReceiptLineId", StringType(), True),
            StructField("productId", StringType(), True),
            StructField("costCodeId", StringType(), True),
            StructField("departmentId", StringType(), True),
            StructField("version", LongType(), True),
            StructField("invoicedStatus", StringType(), True),
            StructField("jobId", StringType(), True),
            StructField("projectId", StringType(), True),
            StructField("projectPhaseId", StringType(), True),
            StructField("projectCostCodeId", StringType(), True),
            StructField("unitOfMeasure", StringType(), True),
            StructField("jcPhaseId", StringType(), True),
            StructField("jcCostTypeId", StringType(), True),
            StructField("jobCostTypeId", StringType(), True),
            StructField("revenueTypeId", StringType(), True),
            StructField("billingStatus", StringType(), True),
            StructField("jobCloseoutDescription", StringType(), True),
            StructField("jobCloseoutTaxable", LongType(), True),
            StructField("equipmentId", StringType(), True),
            StructField("providerTaxCodeId", StringType(), True),
            StructField("equipment", StringType(), True),
            StructField("lineType", StringType(), True),
            StructField("workTaxabilityTypeId", StringType(), True),
            StructField(
                "purchaseOrderReceiptLineBillLines",
                ArrayType(QUANTITY_BILLED_SCHEMA, True),
                True,
            ),
        ]
    )

    # AddressDto (addresses[]). ``addressLine1`` is not in the documented
    # AddressDto schema (only ``addressLine2`` is), but the omission looks like a
    # spec gap; it is declared defensively and is simply null when absent.
    ADDRESS_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("addressLine1", StringType(), True),
            StructField("addressLine2", StringType(), True),
            StructField("city", StringType(), True),
            StructField("state", StringType(), True),
            StructField("zipcode", StringType(), True),
            StructField("addressType", StringType(), True),
        ]
    )

    # AttachmentDto (vendorDocumentAttachment).
    ATTACHMENT_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("customFileName", StringType(), True),
            StructField("fileName", StringType(), True),
            StructField("fileUrl", StringType(), True),
            StructField("fileSize", DoubleType(), True),
            StructField("description", StringType(), True),
            StructField("originalFileName", StringType(), True),
            StructField("isUploaded", BooleanType(), True),
            StructField("comment", StringType(), True),
            StructField("hideFromTechniciansOnMobile", BooleanType(), True),
        ]
    )

    # ---------------------------------------------------------------------------
    # bills (PublicBillResponseDto)
    # ---------------------------------------------------------------------------

    BILLS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("tenantId", StringType(), True),
            StructField("audit", AUDIT_INFO_SCHEMA, True),
            StructField("billLines", ArrayType(BILL_LINE_SCHEMA, True), True),
            StructField("transactionDate", LongType(), True),
            StructField("billNumber", StringType(), True),
            StructField("customIdentifier", StringType(), True),
            StructField("description", StringType(), True),
            StructField("freight", DoubleType(), True),
            StructField("tax", DoubleType(), True),
            StructField("addedBy", StringType(), True),
            StructField("invoicedStatus", StringType(), True),
            StructField("accountingRefIdOfClass", StringType(), True),
            StructField("purchaseOrderReceiptId", StringType(), True),
            StructField("departmentId", StringType(), True),
            StructField("taxRateId", StringType(), True),
            StructField("vendorId", StringType(), True),
            StructField("jobId", StringType(), True),
            StructField("projectId", StringType(), True),
            StructField("vendorDocumentNumber", StringType(), True),
            StructField("vendorDocumentAttachment", ATTACHMENT_SCHEMA, True),
            StructField("orderedById", StringType(), True),
            StructField("issuedBy", LongType(), True),
            StructField("postingDate", LongType(), True),
            StructField("dueDate", LongType(), True),
            StructField("version", LongType(), True),
            StructField("totalCost", DoubleType(), True),
            StructField("syncLog", StringType(), True),
            StructField("syncStatus", StringType(), True),
            StructField("accountingVersion", StringType(), True),
            StructField("isImported", BooleanType(), True),
            StructField("tenantCompanyId", StringType(), True),
            StructField("purchaseOrderId", StringType(), True),
            StructField("approvalStatus", StringType(), True),
            StructField("approvalNote", StringType(), True),
            StructField("approvalNoteById", StringType(), True),
            StructField("approvalNoteDateTime", LongType(), True),
            StructField("projectManagerId", StringType(), True),
            StructField("paymentTermId", StringType(), True),
            StructField("assignedToId", StringType(), True),
            StructField("status", StringType(), True),
            StructField("createdByEmployeeId", StringType(), True),
            StructField("isCreatedFromMobile", BooleanType(), True),
            # Fields returned by the live API but absent from the documented
            # PublicBillResponseDto (observed 2026-09-24 on the dev tenant). Types
            # follow the observed values; fields only ever seen as null follow
            # their CreateBillDto counterpart / naming. ``taxAmountOverridden`` is
            # a StringType because its type could not be observed (always null)
            # and a string column is lossless for either a flag or an amount.
            StructField("uniqueBillNumber", StringType(), True),
            StructField("accountingRefId", StringType(), True),
            StructField("isStandalone", BooleanType(), True),
            StructField("totalAmountPreTax", DoubleType(), True),
            StructField("taxRegionId", StringType(), True),
            StructField("isUseTaxable", BooleanType(), True),
            StructField("useTaxTotal", DoubleType(), True),
            StructField("taxAmountOverridden", StringType(), True),
            StructField("isReceiptBound", BooleanType(), True),
            StructField("vendorDocumentAttachmentId", StringType(), True),
            StructField("amountDue", DoubleType(), True),
            StructField("isRetainageApplicable", BooleanType(), True),
            StructField("isRetainageBill", BooleanType(), True),
            StructField("defaultRetainagePercent", DoubleType(), True),
            StructField("totalRetainageAmount", DoubleType(), True),
            StructField("retainageAmountUnbilled", DoubleType(), True),
            StructField("parentBillId", StringType(), True),
            StructField("vendorLocationId", StringType(), True),
            StructField("vendorContactId", StringType(), True),
            StructField("billToAddressId", StringType(), True),
            StructField("shipToAddressId", StringType(), True),
            StructField("shipFromAddressId", StringType(), True),
            # ``addresses`` (like ``billLines`` and ``vendorDocumentAttachment``)
            # is only returned when requested via the ``include`` table option.
            StructField("addresses", ArrayType(ADDRESS_SCHEMA, True), True),
            # include-only relation objects (JSON strings; null unless requested
            # through the ``include`` table option).
            StructField("purchaseOrder", StringType(), True),
            StructField("purchaseOrderReceipt", StringType(), True),
            StructField("vendor", StringType(), True),
            StructField("job", StringType(), True),
            StructField("project", StringType(), True),
            StructField("department", StringType(), True),
            StructField("orderedBy", StringType(), True),
            StructField("projectManager", StringType(), True),
            StructField("assignedTo", StringType(), True),
            StructField("approvalNoteBy", StringType(), True),
            StructField("paymentTerm", StringType(), True),
            StructField("taxRate", StringType(), True),
        ]
    )

    TABLE_SCHEMAS = {
        "bills": BILLS_SCHEMA,
    }

    TABLE_METADATA = {
        "bills": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
    }

    SUPPORTED_TABLES = list(TABLE_SCHEMAS.keys())


    ########################################################
    # src/databricks/labs/community_connector/sources/buildops/buildops_client.py
    ########################################################

    class BuildOpsAPIError(RuntimeError):
        """Raised when the BuildOps API returns a non-retriable error response."""

        def __init__(self, message: str, status_code: Optional[int] = None) -> None:
            super().__init__(message)
            self.status_code = status_code


    def _body_excerpt(resp: requests.Response, limit: int = 500) -> str:
        try:
            return resp.text[:limit]
        except Exception:  # pylint: disable=broad-except
            return "<unreadable response body>"


    class BuildOpsClient:
        """Thin authenticated wrapper around ``requests`` for the BuildOps API."""

        def __init__(
            self,
            client_id: str,
            client_secret: str,
            tenant_id: str,
            base_url: str,
            timeout: float = REQUEST_TIMEOUT_SECONDS,
        ) -> None:
            self.client_id = client_id
            self.client_secret = client_secret
            self.tenant_id = tenant_id
            self.base_url = base_url.rstrip("/")
            self.timeout = timeout
            self._session: Optional[requests.Session] = None
            self._access_token: Optional[str] = None
            self._token_expires_at: float = 0.0

        # The session is recreated lazily so the client (and the connector that
        # owns it) stays cheaply picklable when Spark ships it to executors.
        def __getstate__(self) -> dict:
            state = self.__dict__.copy()
            state["_session"] = None
            return state

        @property
        def session(self) -> requests.Session:
            if self._session is None:
                self._session = requests.Session()
            return self._session

        # ------------------------------------------------------------------
        # Auth
        # ------------------------------------------------------------------

        def _token_is_fresh(self) -> bool:
            return bool(self._access_token) and time.time() < self._token_expires_at

        def invalidate_token(self) -> None:
            self._access_token = None
            self._token_expires_at = 0.0

        def get_access_token(self) -> str:
            """Return a cached bearer token, exchanging credentials if needed."""
            if self._token_is_fresh():
                return self._access_token  # type: ignore[return-value]

            url = f"{self.base_url}{TOKEN_PATH}"
            payload = {"clientId": self.client_id, "clientSecret": self.client_secret}
            resp = self._send_with_retry(
                "POST",
                url,
                json=payload,
                headers={"Content-Type": "application/json", "Accept": "application/json"},
            )
            if resp.status_code != 200:
                raise BuildOpsAPIError(
                    f"BuildOps token exchange failed (HTTP {resp.status_code}) at "
                    f"{url}. Verify the client_id / client_secret connection options "
                    f"and base_url. Response: {_body_excerpt(resp)}",
                    status_code=resp.status_code,
                )
            try:
                body = resp.json()
                token = body["access_token"]
            except (ValueError, KeyError, TypeError) as e:
                raise BuildOpsAPIError(
                    f"BuildOps token response did not contain 'access_token': "
                    f"{_body_excerpt(resp)}"
                ) from e

            try:
                ttl = float(body.get("expires_in") or DEFAULT_TOKEN_TTL_SECONDS)
            except (TypeError, ValueError):
                ttl = float(DEFAULT_TOKEN_TTL_SECONDS)
            margin = min(TOKEN_REFRESH_MARGIN_SECONDS, ttl / 2)
            self._access_token = token
            self._token_expires_at = time.time() + ttl - margin
            return token

        # ------------------------------------------------------------------
        # Requests
        # ------------------------------------------------------------------

        def request(
            self,
            method: str,
            path: str,
            params: Optional[dict] = None,
            json: Any = None,
        ) -> requests.Response:
            """Issue an authenticated request and return the final response.

            Retries 429 / 5xx with backoff. On a 401 the cached token is dropped,
            a new one is exchanged, and the request is retried exactly once.
            Callers inspect ``status_code`` for everything else.
            """
            url = f"{self.base_url}{path}"
            resp = self._send_authenticated(method, url, params=params, json=json)
            if resp.status_code == 401:
                self.invalidate_token()
                resp = self._send_authenticated(method, url, params=params, json=json)
                if resp.status_code == 401:
                    raise BuildOpsAPIError(
                        f"BuildOps rejected the access token (HTTP 401) for "
                        f"{method} {path} even after re-authenticating. Verify the "
                        f"client credentials. Response: {_body_excerpt(resp)}",
                        status_code=401,
                    )
            return resp

        def _send_authenticated(
            self, method: str, url: str, params: Optional[dict], json: Any
        ) -> requests.Response:
            headers = {
                "Authorization": f"Bearer {self.get_access_token()}",
                "tenantId": self.tenant_id,
                "Accept": "application/json",
            }
            if json is not None:
                headers["Content-Type"] = "application/json"
            return self._send_with_retry(method, url, params=params, json=json, headers=headers)

        def _send_with_retry(
            self,
            method: str,
            url: str,
            params: Optional[dict] = None,
            json: Any = None,
            headers: Optional[dict] = None,
        ) -> requests.Response:
            backoff = INITIAL_BACKOFF_SECONDS
            last_exc: Optional[Exception] = None
            resp: Optional[requests.Response] = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = self.session.request(
                        method,
                        url,
                        params=params,
                        json=json,
                        headers=headers,
                        timeout=self.timeout,
                    )
                except (requests.ConnectionError, requests.Timeout) as e:
                    last_exc = e
                    resp = None
                else:
                    if resp.status_code not in RETRIABLE_STATUS_CODES:
                        return resp

                if attempt == MAX_RETRIES - 1:
                    break
                time.sleep(self._retry_delay(resp, backoff))
                backoff = min(backoff * 2, MAX_BACKOFF_SECONDS)

            if resp is not None:
                return resp
            raise BuildOpsAPIError(
                f"BuildOps request {method} {url} failed after {MAX_RETRIES} "
                f"attempts: {last_exc}"
            ) from last_exc

        @staticmethod
        def _retry_delay(resp: Optional[requests.Response], backoff: float) -> float:
            if resp is not None:
                retry_after = resp.headers.get("Retry-After")
                if retry_after:
                    try:
                        return min(max(float(retry_after), 0.0), MAX_BACKOFF_SECONDS)
                    except ValueError:
                        pass
            # Small jitter so parallel readers don't retry in lock-step.
            return min(backoff + random.uniform(0, backoff / 4), MAX_BACKOFF_SECONDS)


    ########################################################
    # src/databricks/labs/community_connector/sources/buildops/buildops.py
    ########################################################

    _INCLUDE_LOOKUP = {v.lower(): v for v in BILL_INCLUDE_VALUES}


    def _split_csv(raw: Any) -> list[str]:
        """Split a comma-separated option into stripped, de-duplicated values."""
        if raw is None:
            return []
        seen: dict[str, None] = {}
        for part in str(raw).split(","):
            value = part.strip()
            if value:
                seen.setdefault(value, None)
        return list(seen)


    def _prepare_value(value: Any, data_type: DataType) -> Any:
        """Make a raw API value safe for the framework's schema-driven parser.

        Only two structural adjustments are made; all type coercion is left to
        the framework:

        * a dict / list landing in a ``StringType`` column (undocumented nested
          objects such as ``vendor`` or ``audit.createdBy``) is JSON-encoded;
        * an empty dict landing in a ``StructType`` column becomes ``None``
          (the framework rejects ``{}`` for struct fields).
        """
        if value is None:
            return None
        if isinstance(data_type, StringType):
            if isinstance(value, (dict, list)):
                return json.dumps(value, ensure_ascii=False, separators=(",", ":"))
            return value
        if isinstance(data_type, StructType):
            if not isinstance(value, dict):
                return value
            if not value:
                return None
            for field in data_type.fields:
                if field.name in value:
                    value[field.name] = _prepare_value(value[field.name], field.dataType)
            return value
        if isinstance(data_type, ArrayType) and isinstance(value, list):
            return [_prepare_value(v, data_type.elementType) for v in value]
        return value


    class BuildOpsLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the BuildOps public API."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            missing = [
                key
                for key in ("client_id", "client_secret", "tenant_id")
                if not str(options.get(key) or "").strip()
            ]
            if missing:
                raise ValueError(
                    f"BuildOps connector is missing required connection option(s): "
                    f"{', '.join(missing)}."
                )
            base_url = str(options.get("base_url") or "").strip() or DEFAULT_BASE_URL
            self._client = BuildOpsClient(
                client_id=str(options["client_id"]).strip(),
                client_secret=str(options["client_secret"]).strip(),
                tenant_id=str(options["tenant_id"]).strip(),
                base_url=base_url,
            )

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            bill_ids = self._parse_bill_ids(table_options)
            include = self._parse_include(table_options)
            # Snapshot: the whole table is returned in one batch with no offset.
            return self._iter_bills(bill_ids, include), None

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        @staticmethod
        def _validate_table(table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {SUPPORTED_TABLES}"
                )

        @staticmethod
        def _parse_bill_ids(table_options: dict[str, str]) -> list[str]:
            bill_ids = _split_csv((table_options or {}).get("bill_ids"))
            if not bill_ids:
                raise ValueError(
                    "Table 'bills' requires the 'bill_ids' table option: a "
                    "comma-separated list of BuildOps bill UUIDs. The BuildOps "
                    "public API has no endpoint for listing bills, so the ids to "
                    "read must be supplied explicitly."
                )
            return bill_ids

        @staticmethod
        def _parse_include(table_options: dict[str, str]) -> list[str]:
            values = _split_csv((table_options or {}).get("include"))
            invalid = [v for v in values if v.lower() not in _INCLUDE_LOOKUP]
            if invalid:
                raise ValueError(
                    f"Invalid value(s) for the 'include' table option: {invalid}. "
                    f"Allowed values: {list(BILL_INCLUDE_VALUES)}."
                )
            # Canonicalise casing and drop case-insensitive duplicates.
            return list(dict.fromkeys(_INCLUDE_LOOKUP[v.lower()] for v in values))

        def _iter_bills(self, bill_ids: list[str], include: list[str]) -> Iterator[dict]:
            schema = TABLE_SCHEMAS["bills"]
            for bill_id in bill_ids:
                record = self._fetch_bill(bill_id, include)
                yield _prepare_value(record, schema)

        def _fetch_bill(self, bill_id: str, include: list[str]) -> dict:
            path = BILL_PATH.format(bill_id=quote(bill_id, safe=""))
            # The live API only honours a single comma-separated value
            # (include=a,b); the repeated-key form (include=a&include=b) is
            # accepted with HTTP 200 but silently ignored.
            params = {"include": ",".join(include)} if include else None
            resp = self._client.request("GET", path, params=params)

            if resp.status_code == 404:
                raise BuildOpsAPIError(
                    f"BuildOps bill '{bill_id}' was not found (HTTP 404). It may "
                    f"have been deleted, belong to a different tenant, or be a "
                    f"wrong id -- check the 'bill_ids' table option.",
                    status_code=404,
                )
            if resp.status_code == 403:
                raise BuildOpsAPIError(
                    f"Access to BuildOps bill '{bill_id}' is forbidden (HTTP 403). "
                    f"Verify the credentials are authorised for tenant_id "
                    f"'{self._client.tenant_id}'. Response: {resp.text[:500]}",
                    status_code=403,
                )
            if resp.status_code != 200:
                raise BuildOpsAPIError(
                    f"Failed to read BuildOps bill '{bill_id}' "
                    f"(HTTP {resp.status_code}): {resp.text[:500]}",
                    status_code=resp.status_code,
                )
            try:
                record = resp.json()
            except ValueError as e:
                raise BuildOpsAPIError(
                    f"BuildOps returned a non-JSON body for bill '{bill_id}': {resp.text[:500]}"
                ) from e
            if not isinstance(record, dict):
                raise BuildOpsAPIError(
                    f"BuildOps returned an unexpected payload for bill '{bill_id}': "
                    f"expected a JSON object, got {type(record).__name__}."
                )
            return record


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = BuildOpsLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
